name: Deploy To Server

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Prepare EC2 server
      - name: SSH to server & prepare environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Installing Docker & Compose"

            sudo apt-get update -y
            sudo apt-get install -y docker.io docker-compose-plugin

            sudo systemctl enable docker
            sudo systemctl start docker

            sudo usermod -aG docker $USER

            mkdir -p ~/bankapp
            rm -f ~/bankapp/docker-compose.yml

      # Copy docker-compose.yml
      - name: Copy docker-compose file to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/bankapp/"
          overwrite: true

      # Deploy container
      - name: Deploy application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Deploying application"

            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo docker login \
              --username "${{ secrets.DOCKER_USERNAME }}" \
              --password-stdin

            cd ~/bankapp

            # Stop existing containers (ignore errors if not running)
            sudo docker compose down || true

            # Clean up old images
            sudo docker image prune -a -f

            # Pull newest image from Docker Hub using the same username
            sudo DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}" docker compose pull

            # Start containers with the freshly pulled image
            sudo DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}" docker compose up -d --force-recreate --remove-orphans
            sudo docker exec -it bankapp-ollama ollama pull tinyllama

            echo "Deployment successful"