name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  code-quality:
     uses: ./.github/workflows/code-quality.yml
  dependency-scan:
     uses: ./.github/workflows/dependency-scan.yml
  secrets-scan:
     uses: ./.github/workflows/secrets-scan.yml
  docker-lint:
     uses: ./.github/workflows/docker-lint.yml
  docker-build-trivy-push:
     needs: [code-quality, dependency-scan, secrets-scan, docker-lint]
     uses: ./.github/workflows/docker-build-push.yml
     secrets: inherit
  deploy-server:
     needs: docker-build-trivy-push
     uses: ./.github/workflows/deploy-server.yml
     secrets: inherit
